### PR TITLE
Added View Archive link textView

### PR DESCRIPTION
**Pull request by dinesh-thiyagarajan**
#1038  

This PR adds View Archive textView below the cards list and opens archive screen on click of the textView.

### Checklist
- [x] Unit Tests Passed
- [x] Lint Checks Passed 
- [x] spotbugsRelease Passed
- [x] I have made my changes on a new branch.
- [x] My code follows the code style of this project.
- [x] Basic Sanity Check for the app Passed

@TheLastProject Hope this helps. Can you please start the workflow :)

### CODE REVIEW

**Comment by TheLastProject** [comment]
I'm afraid you've fallen into the exact same trap as I have when I originally implemented this, and what I talked about in the issue itself several times:

image

As you can confirm using the Layout Inspector, your implementation causes every single card ever to be loaded, instead of only the visible cards, meaning this implementation severely harms performance. So sadly this isn't an acceptable fix for #1038.

**Comment by TheLastProject** [comment]
For comparison, the old layout only loads 8 cards even though 12 exist, replacing cards while they scroll in and out of view:
image

**Comment by dineshkarthi95** [comment]
@TheLastProject Oh got it my bad , missed reading the details. will check if I get more time this week. It's interesting how a view added outside of the recycler view is affecting the performance of the recycler view.

**Comment by dineshkarthi95** [comment]
@TheLastProject Hey I understood the issue 😅. The issue was created due to the NestedScrollView

My understanding is that the NestedScrollView draws all child elements, So if RecyclerView has been used inside NestedScrollView all the elements of adapter will be loaded at first time itself. which defeats the purpose of recyclerView by disabling recycling of views. Tried other approaches of using ConcatAdapter (Merging multiple adapters and setting it to recyclerView) didn't work since we are using GridLayoutManager, tried Multiple ViewHolders but single adapter approach as well by overriding the getItemViewType that as well moved the textView to adjacent places and not to the bottom position. Its a bit tricky one as you mentioned 😃

**Comment by pfaffenrodt** [comment]
@dineshkarthi95 This is still possible. You can define a span size per position.

* [GridLayoutManager.SpanSizeLookup](https://developer.android.com/reference/kotlin/androidx/recyclerview/widget/GridLayoutManager#setSpanSizeLookup(androidx.recyclerview.widget.GridLayoutManager.SpanSizeLookup))
* [SpanSizeLookup#getSpanIndex(int,int)](https://developer.android.com/reference/kotlin/androidx/recyclerview/widget/GridLayoutManager.SpanSizeLookup#getSpanIndex(int,int))

```
gridLayoutManager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
        @Override
        public int getSpanSize(int position) {
            if (position == 0) {
                return 2;
            } else {
              return 1;
            }
        }
    });
```

**Comment by dineshkarthi95** [comment]
Hey @pfaffenrodt thanks for your help will try it out and let you know the outcome :)

**Comment by TheLastProject** [comment]
Closing in favor of #1477

**Pull request closed without merging**
