### PR TITLE
Redesign of home screen and view UI

### LINKED ISSUE #620: (Optionally) hide name over logo
for beauty, you need to move the name of the card below the logo. now it looks ugly because of the overlay.

### LINKED ISSUE #637: Max font size selector is looping (from min directly to max)
The font size selector is looping (from min directly to max). When I arrive down to 50%, and I continue to scroll, I continue to 200%. This is a bit a weird behavior. Shouldn't it be better to just have to separate ends at 50 end 200 on each side?

System information:
- Android 5.0.1
- Device: Samsung Galaxy Core Prime

### LINKED ISSUE #711: Emoji in card name doesn't display well in card view
This is a minor bug, but emojis have a small 'white dots' in the background. I don't know if this is reproducable on other devices, but just wanted to document this 'little bug' here :)

image

System information:

Android 5.0.1
Device: Samsung Galaxy Core Prime

### LINKED ISSUE #964: Enhancement: add view option with names not visible
Love the app, just had a simple feature request for an option to be available that would show the card image at full "card" size, but not have the name visible. I have added images for all of my cards so this would allow for a cleaner look with the cards remaining easily identifiable. As this may not be a common use-case, a toggle setting for "hide card names" could live within the settings menu instead of being on the main screen.

### LINKED ISSUE #1232: Modern style request
unnamed    screenshot-01

Styling looks like from the past, if possible - make an update for a simple and clean theme )))

### LINKED ISSUE #1285: Card View (Design Improvement)
I know that updating the design may not be a top priority for the developers, but I hope that they can take my suggestion into consideration. ❤️

I'm really fond of the app's main screen, but I have a small suggestion that could significantly improve the card view design. 
The card view seems to have a lot of information packed in, with various elements on top of each other  and the barcode occupying a significant amount of screen space. It would be great if the cards were centered and their corners rounded, as this could make a big difference in terms of the app's user-friendliness. I believe that this small change and implementing a new "material" design would not only give the app a modern and sleek look, but also make a big difference in terms of the overall user experience.

_I can't believe it's been almost a year since I downloaded this app, and it has truly become a staple in my daily "shopping" routine.  I want to see it evolve and improve over time - I'm really excited about the potential for this update, and I can't wait to see what the future holds!_

Untitled design (1) (1)
> I wanted to share a rough draft of my idea; the fonts used are Kollektif and Rubik

### PR DESCRIPTION
**Pull request by TheLastProject**
It looks fine but:
- [x] Fix tests
- [ ] Support changing icon by clicking icon in view (probably not in this MR)
- [x] Update screenshots
- [ ] Test test test!

Fixes #1285 (by implementing)
Fixes #1232 (I mean, close enough)
Fixes #964 and fixes #620 (no longer relevant after redesign)
Fixes #711
Fixes #637 (by removing the font size setting)

### CODE REVIEW

**Comment by Altonss** [comment]
Is there any way to test the build apk? Is it available in the artifacts? I'm curious to try out this new design :)

**Comment by Altonss** [comment]
Thanks for the screenshots, I like this new design :) I looks really polished and the main screen feels less cluttered!

**Comment by Altonss** [comment]
Only issue might be the rounded corners of the barcode in darkmode? (screenshot 8) But it's really a detail

**Comment by TheLastProject** [comment]
> Only issue might be the rounded corners of the barcode in darkmode? (screenshot 8) But it's really a detail

Yeah, I'm not sure why it's doing that :( But I've spent like 2 weeks on coding this redesign and I kinda want to call it done by now because it took so much of my time and energy so I'm just going to merge this and maybe someone else can fix it later or I find a way to fix it later because it feels like an improvement in every way except that small bug :sweat_smile:

**Comment by Altonss** [comment]
> But I've spent like 2 weeks on coding this redesign and I kinda want to call it done by now because it took so much of my time and energy so I'm just going to merge this and maybe someone else can fix it later or I find a way to fix it later because it feels like an improvement in every way except that small bug sweat_smile

Yes I agree, no worries, it's just something I noticed (but we could say this design is intended :laughing:, like a retro coupon) :)

**Pull request merged**
