### PR TITLE
Archive support

### LINKED ISSUE #644: [Feature request] Add the possibility to archive cards
I would love to be able to hide some old cards by archiving them!

### PR DESCRIPTION
**Pull request by TheLastProject**
This is just #885 with all changes squashed and a few cleanups.

Fixes #644.

### CODE REVIEW

**Comment by TheLastProject** [comment]
Export is broken, can't merge this yet.

**Comment by TheLastProject** [comment]
I've been doing some tested and fixed a few last small bugs I found in here @Jasielprogramador, hope you don't mind :)

@Altonss I created a debug build here. If you can find any bugs still that would be awesome, but I think it's stable. Will give it a few days on my own device for some extra certainty: [app-debug.zip](https://github.com/CatimaLoyalty/Android/files/8929693/app-debug.zip)

**Comment by Jasielprogramador** [comment]
Sure no problem, thanks a lot

**Comment by Altonss** [comment]
> I've been doing some tested and fixed a few last small bugs I found in here @Jasielprogramador, hope you don't mind :)
> 
> @Altonss I created a debug build here. If you can find any bugs still that would be awesome, but I think it's stable. Will give it a few days on my own device for some extra certainty: [app-debug.zip](https://github.com/CatimaLoyalty/Android/files/8929693/app-debug.zip)

Thanks a lot for all this hard work @Jasielprogramador and @TheLastProject. I will try to install the build and see if I see any bug!

**Comment by Altonss** [comment]
All seem to work great. Only detail I noticed, which is really a visual detail, is that the star and archive icon are not exactly the same size. But that's a detail that is very secondary and not blocking this PR at all :)

**Comment by TheLastProject** [comment]
Well, I'll go ahead and merge this so translators can start translating. Let's hope that if there are any bugs remaining we still notice it before the next release or at least before it leaves the Google Play beta :)

**Comment by Altonss** [comment]
> Well, I'll go ahead and merge this so translators can start translating. Let's hope that if there are any bugs remaining we still notice it before the next release or at least before it leaves the Google Play beta :)

Unfortunately the latest commits do not seam to have reached weblate yet...

**Pull request merged**
