### PR TITLE
Draft: Add entry at end of card list to go to archive

### LINKED ISSUE #948: Protect against accidental archiving
Right now archiving is too easily down and users may love cards by accidentally archiving and not knowing how to get back there. It would be good to have a way to teach users where to find archived card.

I think preferably, the main screen would show an extra "card" all the way at the end which is not a real card but will instead open the archive. Using an "coloured letter" of +2 (or however many are in archive) with the text "In archive" may work. Or some other button or text on the main screen opening the same group in the archive.

Maybe we should also ask for confirmation when archiving a card.

### PR DESCRIPTION
**Pull request by TheLastProject**
Fixes #948 when done.

image

It works but this code kinda... worries me. There must be a much cleaner way to do something like this...

Also TODO: Exclude from selection so Catima won't offer to edit, favourite, archive, delete or... share this button

### CODE REVIEW

**Comment by Altonss** [comment]
On the screenshot you posted I find the "Open archive" card very confusing because it looks like a normal card.
Wouldn't it make more sens at the bottom of the card "list" to have an open archive button that is not as high and takes up all the width? Like more a horizontal element like in Signal where at the end of the conversation list there is the "Archived conversations" button...

**Comment by TheLastProject** [comment]
Could you show a picture of what you mean?

**Comment by Altonss** [comment]
> Could you show a picture of what you mean?

Here is just a screenshot of the bottom of my screen :

IMG_20220903_173829

**Comment by TheLastProject** [comment]
Hmm, that might've been better instead x.x

**Comment by TheLastProject** [comment]
Superseded by #1009

**Pull request closed without merging**
