### PR TITLE
add python script & update stocard csv

### PR DESCRIPTION
**Pull request by obfusk**

### CODE REVIEW

**Comment by TheLastProject** [comment]
Fancy! I do worry about the .py file being in the app resources though, I feel that may trip some antivirus scanners if it gets included "because it is weird for a .py file to be in an Android app". Maybe it'll be better to move that around? I also probably should've ensured the `readme.md` wasn't included with the app (unnecessarily bloating it) but I'm not quite sure where else to put that to explain the .csv a bit, maybe it should move to `docs/STOCARD.md`?

**Comment by obfusk** [comment]
Yeah, I was wondering where best to put those myself :)

Want me to put the readme in `docs/STOCARD.md` and the script in `.scripts/`?

**Comment by obfusk** [comment]
Added a commit that does that. Let me know if you wanted something else :)

**Comment by obfusk** [comment]
> I feel that may trip some antivirus scanners if it gets included "because it is weird for a .py file to be in an Android app"

I mean, my python-for-android apps include `.pyc` files. But still not the best place to put it.

Also : I force pushed w/o changes because the unit test got stuck again.

**Comment by obfusk** [comment]
> Also : I force pushed w/o changes because the unit test got stuck again.

Turned out not to be needed. It actually succeeded on retry this time. Nice to see that can happen too.

Force pushed again because of an ssl error :)

**Pull request merged**
