### PR TITLE
CI: add workflow to update gradle

### PR DESCRIPTION
**Pull request by obfusk**

### CODE REVIEW

**Comment by obfusk** [comment]
I guess turning this into a separate github action might be a good idea. Will look into that later.

**Comment by obfusk** [comment]
Turned it into an action. Test run with the recent gradle update undone produces the exact same result (apart from the timestamp comment):

https://github.com/obfusk/catima/commit/63bb9d2bc734d68e7bbaa3ef2c2fc7618035c739

https://github.com/obfusk/catima/compare/4a920e3f834c0651600ce200aca99bf493f62a37...63bb9d2bc734d68e7bbaa3ef2c2fc7618035c739#diff-40640fe1078ece83d7ea8fb67daacd77923a86d13447baf9769660b3b46f2ece

**Comment by obfusk** [comment]
Feel free to review the code in https://github.com/obfusk/gradle-update-action :)

**Comment by TheLastProject** [comment]
Looks great, thanks :)

**Pull request merged**
