### PR TITLE
Crash on clicking "Add from image" button in scan activity #856

### PR DESCRIPTION
**Pull request by alajemba-vik**
This PR contains a fix for issue #856, which concerns a crash that occurs when no activity can handle the intent to pick an image file.

### The simplest way to reproduce
* Disable all the gallery apps (e.g., Google Photos)
* Go to the ScanActivity by clicking the FAB on the home screen
* The app crashes when you click the button "Select image from gallery"

### Expected behavior
Clicking that button should have launched a gallery app, or displayed a disambiguation dialog if there is more than one app that can handle the intent being invoked.

### Solution
Wrapped the call to launch in a try-catch block.

### CODE REVIEW

**Comment by alajemba-vik** [comment]
Sure. Let me get that done in the same branch and then make another push @TheLastProject.

**Comment by TheLastProject** [comment]
Ouch, that is pretty ugly code. No clue what I was thinking when I wrote that :(

Still seems better to catch the specific ActivityNotFound exception earlier anyway, so Catima can give the user a meaningful message instead of "doing nothing". Then at some point later (not part of this PR) we can delete that overly broad exception catching way too much and hopefully not have any issues (but possibly catch some hidden bugs).

**Comment by alajemba-vik** [comment]
Understood. Update coming up. @TheLastProject

**Comment by alajemba-vik** [comment]
Updated. Kindly check it out. @TheLastProject

**Comment by TheLastProject** [comment]
This looks great, thanks!

**Pull request merged**
