### PR TITLE
language support added

### PR DESCRIPTION
**Pull request by criticalAY**
created a new PR for # Language android13 #1030

### CODE REVIEW

**Comment by TheLastProject** [comment]
Cool start, but there seem to be some issues with this implementation.

Specifically, the language choice in Android's language selection and in the app aren't in sync. This can cause quite confusing behaviour when users change multiple of the values:
| Android | App | Result |
| - | - | - |
| System | Dutch | Dutch |
| Dutch | German | German |
| Dutch | System | German |

**Comment by criticalAY** [comment]
> 

any possible solution or a way to tackle it you would like to suggest?

**Comment by joserebelo** [comment]
FYI, there's a section on the [Per-app language preferences](https://developer.android.com/guide/topics/resources/app-languages#api-implementation) page on how to handle in-app language pickers.

**Comment by TheLastProject** [comment]
Nice find, that's very helpful :)

**Comment by obfusk** [comment]
Superseded by #1447.

**Pull request closed without merging**
