### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Catima/Android](https://hosted.weblate.org/projects/catima/catima/).

It also includes following components:

* [Catima/Android (Debug)](https://hosted.weblate.org/projects/catima/android-debug/)

* [Catima/Android (Fastlane)](https://hosted.weblate.org/projects/catima/fastlane/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by obfusk** [comment]
Why add an empty `app/src/debug/res/values-nl/strings.xml`?

**Comment by TheLastProject** [comment]
Weblate always does that when a language gets created. I already added more values to it.

**Comment by obfusk** [comment]
This is in the *debug* directory though. Which should not be translated AFAIK.

Weblate says:

> File mask: `app/src/main/res/values-*/strings.xml`

**Comment by obfusk** [comment]
Ah. You added Debug. Missed that. Wasn't expecting it.

**Pull request merged**
