### PR TITLE
Bump to latest stable Gradle version

### PR DESCRIPTION
**Pull request by theimpulson**
## Summary

* Enforce sha256Sum verification (https://gradle.org/release-checksums/)
*  Run ./gradlew wrapper as well

### CODE REVIEW

**Comment by TheLastProject** [comment]
I was wondering why this wasn't updated more automatically, turns out dependabot doesn't support this yet: https://github.com/dependabot/dependabot-core/issues/2223

Let me check if the files are correct (especially the binary) and then I'll hit merge :)

**Comment by TheLastProject** [comment]
Okay, can confirm `gradle/wrapper/gradle-wrapper.properties` is good and so is `gradle/wrapper/gradle-wrapper.jar` (confirmed by both me and CI).

Where did you get `gradlew` and `gradlew.bat` from? I know those are available... somewhere but I can't find them right now.

**Comment by theimpulson** [comment]
> Okay, can confirm `gradle/wrapper/gradle-wrapper.properties` is good and so is `gradle/wrapper/gradle-wrapper.jar` (confirmed by both me and CI).
> 
> Where did you get `gradlew` and `gradlew.bat` from? I know those are available... somewhere but I can't find them right now.

@TheLastProject `./gradlew wrapper` task updates them.

**Comment by TheLastProject** [comment]
Interesting, if I run `./gradlew wrapper --gradle-version=8.4 --distribution-type=bin` from the main branch I get slightly different files:

```diff
❯ diff my_gradlew theimpulson_gradlew 
86,89c86,87
< APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit
< 
< # Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
< DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
---
> # Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25036)
> APP_HOME=$( cd "${APP_HOME:-./}" > /dev/null && pwd -P ) || exit
136c134,136
<     which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
---
>     if ! command -v java >/dev/null 2>&1
>     then
>         die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
139a140
>     fi
147c148
<         # shellcheck disable=SC3045
---
>         # shellcheck disable=SC2039,SC3045
155c156
<         # shellcheck disable=SC3045
---
>         # shellcheck disable=SC2039,SC3045
200,204c201,209
< # Collect all arguments for the java command;
< #   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
< #     shell script including quotes and variable substitutions, so put them in
< #     double quotes to make sure that they get re-expanded; and
< #   * put everything else in single quotes, so that it's not re-expanded.
---
> 
> # Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
> DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
> 
> # Collect all arguments for the java command:
> #   * DEFAULT_JVM_OPTS, JAVA_OPTS, JAVA_OPTS, and optsEnvironmentVar are not allowed to contain shell fragments,
> #     and any embedded shellness will be escaped.
> #   * For example: A user cannot expect ${Hostname} to be expanded, as it is an environment variable and will be
> #     treated as '${Hostname}' itself on the command line.
```

(gradlew.bat is equal in both cases)

**Comment by theimpulson** [comment]
I ran the command after upgrading the gradle version using Android Studio.

**Comment by TheLastProject** [comment]
I guess I misunderstood how to use `./gradlew wrapper`, I expected `./gradlew wrapper --gradle-version=8.4 --distribution-type=bin` to give me the wrapper files for Gradle 8.4 but it ignores those flags and just gives you them for the current Gradle version.

Thanks, 100% confirmed then :)

**Comment by obfusk** [comment]
> Enforce sha256Sum verification

I assume this no longer crashes Android Studio?

**Comment by TheLastProject** [comment]
AFAIK Google never fixed that but, but I can just edit the file from the CLI if Android Studio crashes so no big deal :P

**Comment by obfusk** [comment]
> I guess I misunderstood how to use `./gradlew wrapper`, I expected `./gradlew wrapper --gradle-version=8.4 --distribution-type=bin` to give me the wrapper files for Gradle 8.4 but it ignores those flags and just gives you them for the current Gradle version.

That is indeed confusing. Per [the docs](https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:upgrading_wrapper):

>  The following command upgrades the Wrapper to a specific version:

```
$ ./gradlew wrapper --gradle-version 8.4
```

> Once you have upgraded the wrapper, you can check that it’s the version you expected by executing ./gradlew --version.

> Don’t forget to run the wrapper task again to download the Gradle distribution binaries (if needed) and update the gradlew and gradle.bat files.

---

```sh
# doesn't work
$ ./gradlew wrapper --gradle-version latest
'latest' is not a valid Gradle version string (examples: '1.0', '1.0-rc-1')
```

```sh
# not sure why this updated gradlew{,.bat} to a version that doesn't match 8.4, maybe they were outdated?
$ ./gradlew wrapper --gradle-version 8.4
$ git status
        modified:   gradle/wrapper/gradle-wrapper.jar
        modified:   gradle/wrapper/gradle-wrapper.properties
        modified:   gradlew
        modified:   gradlew.bat
```

```
# this now uses 8.4 and updates gradlew{,.bat} to the versions in this PR
$ ./gradlew wrapper
Downloading https://services.gradle.org/distributions/gradle-8.4-bin.zip
[...]
```

The result is identical to this PR except for the sha256sum check (and the timestamp) and https://github.com/obfusk/gradle-wrapper-verify agrees the wrapper .jar has a known checksum. I did not doubt any of that of course, just wanted to see if I could figure out the right commands, reproduce the steps manually, and get the same result as expected.

---

> I was wondering why this wasn't updated more automatically, turns out dependabot doesn't support this yet

Want me to make a custom action to do that? Should be fairly easy.

**Comment by TheLastProject** [comment]
Okay, so it's not just me, it seems like it may be a documentation issue?

> and https://github.com/obfusk/gradle-wrapper-verify agrees the wrapper .jar has a known checksum

Yeah, already using gradle's official action for that

> Want me to make a custom action to do that? Should be fairly easy.

Sounds nice, the more automation the better :+1:

**Comment by obfusk** [comment]
> Okay, so it's not just me, it seems like it may be a documentation issue?

The documentation is sort of correct but the behaviour is still confusing IMO.

> Yeah, already using gradle's official action for that

I know, just confirming my script (which is easier to run locally) agrees :)

> Sounds nice, the more automation the better 👍

Will look into it next week then :)

**Comment by obfusk** [comment]
Regarding the confusing behaviour:

This first updated the gradle wrapper to 8.0 (it was behind, mismatched with the gradle version, otherwise that would have been a no-op). And then updated the gradle version (& checksum if specified) to 8.4.

```sh
./gradlew wrapper --gradle-version 8.4
```

And then this actually downloaded and used gradle 8.4 and updated the wrapper to 8.4.

```sh
./gradlew wrapper
```

(And for reference, my action is here: https://github.com/obfusk/gradle-update-action)

**Pull request merged**
