### PR TITLE
Improve barcode rendering (square codes & padding)

### LINKED ISSUE #1332: Square barcodes, landscape and full-screen views
Whilst landscape orientation works well for 1D barcodes, it makes non-trivial 2D codes like Aztec render too small to use due to the surrounding screen furniture (action bar, bottom bar, ID as text and so on).

Screenshot_2023-06-01-18-57-58-26_0e0fb5e4c7b0c70cd406dc034ad65059

Here's one such example (value randomised but in the same format as a real ID, and the code is of comparable complexity).  At that size it's rather difficult to scan, meaning I need to jump into the full-screen view which is a bit more cumbersome.

The height slider also overlaps slightly with square codes in the landscape full-screen view when at the max value (i.e. lowest height), meaning you need to reduce it slightly to fit.

Screenshot_2023-06-01-18-58-14-88_0e0fb5e4c7b0c70cd406dc034ad65059

It would be useful to have an option to force landscape for 1D codes and portrait for 2D, or otherwise to arrange the landscape view for 2D codes to place certain information beside them.  Alternatively, having separate orientation settings for the main and full-screen views would allow forcing landscape only in the full-screen view, where square codes fit better in either orientation.

### PR DESCRIPTION
**Pull request by obfusk**
Fixes #1332.

<details>
<summary>screenshots</summary>

Screenshot_20230608_191619
Screenshot_20230608_191626
Screenshot_20230608_191642
Screenshot_20230608_191650
Screenshot_20230608_191702
Screenshot_20230608_191709

</details>

### CODE REVIEW

**Comment by obfusk** [comment]
Might also fix #329.

**Comment by obfusk** [comment]
### Explanation

The current code doesn't take square barcodes into account, thus incorrectly reducing the height to match the max width using a wrong aspect ratio. I changed that to use the minimum of the height, width, and max width for both height and width (since it's square). Which results in better rendering (and no weird padding) for square barcodes like Aztec.

It also adds padding for the rounded corners by reducing the height of the image itself, which I replaced by adding actual padding to either the height or width of the `imageView`, depending on which is more appropriate given the shape of the barcode and whether the `imageView` is landscape or portrait. Which should result in no "unnecessary" padding being added in many cases, especially for square barcodes.

**Comment by obfusk** [comment]
> incorrectly reducing the height to match the max width using a wrong aspect ratio

It was scaling the height to match the max width, but using the aspect ratio of the `imageView`, ignoring the fact that the image should be square for a square barcode.

**Comment by obfusk** [comment]
> It was scaling the height to match the max width, but using the aspect ratio of the `imageView`, ignoring the fact that the image should be square for a square barcode.

This was causing both weird padding (on some devices, it was not consistent between my phone and the emulator) and blurred images because of the wrong resolution, which is why I think it might fix #329.

**Comment by TheLastProject** [comment]
Well, especially with your explanation it makes sense to me. I'm not seeing anything wrong from some quick testing. I'm going to merge it, if more testing shows issues later I can always revert easily anyway :)

**Comment by obfusk** [comment]
I found one case that got worse. According to `CatimaBarcode.isSquare()`, Data Matrix is square. This does not seem to be true for all values:

Screenshot_20230622-234524_Catima Debug

**Pull request merged**
