### PR TITLE
CatimaBarcode: DATA_MATRIX is not always square

### PR DESCRIPTION
**Pull request by obfusk**
Following up on https://github.com/CatimaLoyalty/Android/pull/1359#issuecomment-1603359582: `DATA_MATRIX` can be rectangular as well.

I also removed `MAXICODE` since it's not supported.

I tested the changes on my phone. It looks slightly better than before #1359 now IMO. Square versions looked okay too.

<details>
<summary>screenshot: before</summary>

Screenshot_20230623-002629_Catima

</details>

<details>
<summary>screenshot: after #1359</summary>

Screenshot_20230622-234524_Catima Debug

</details>

<details>
<summary>screenshot: with this fix</summary>

Screenshot_20230623-002636_Catima Debug

</details>

<details>
<summary>screenshot: with second commit too [Edit]</summary>

Screenshot_20230623-012701_Catima Debug

</details>

### CODE REVIEW

**Comment by obfusk** [comment]
It's slightly blurry (as it was before), because that part of fix for square codes doesn't work now, but I'm not sure how we can know beforehand whether it will be square or rectangular, so fixing that would not be trivial.

**Comment by obfusk** [comment]
> I also removed `MAXICODE` since it's not supported.

I noticed `BarcodeImageWriterTask.getMaxWidth()` also lists some unsupported codes (but `getFallbackString()` doesn't).

**Comment by obfusk** [comment]
I added a second commit to treat `DATA_MATRIX` as 1D for max width, which makes it less blurred.

The commit also removes the unsupported barcode types from that function.

**Comment by obfusk** [comment]
I added a screenshot to the issue description.

**Comment by TheLastProject** [comment]
> The commit also removes the unsupported barcode types from that function.

I'm not a fan of that change actually, because it is unrelated to this fix. The way Catima is set up should (IIRC) also means that as soon as zxing adds support these barcodes should start working. So this change, as I understand it, actually will cause unexpected breakage in the future.

**Comment by obfusk** [comment]
> because it is unrelated to this fix

Fair enough. I thought it was just related enough since I touched that code and it served no purpose to leave them in, but I was prepared for you to disagree :)
Would you prefer me to remove it?

> So this change, as I understand it, actually will cause unexpected breakage in the future.

Any type not listed in `CatimaBarcode.barcodeFormats` is not supported by the app. So it should not break.
And I removed the unused formats from `getMaxWidth()` because `getFallbackString()` doesn't support them either, making the current code inconsistent and *more* likely to break when adding support for a new barcode type IMO.
Simply adding the codes to `barcodeFormats` would break some functions, but not others. with the current code.

**Comment by obfusk** [comment]
I would have made a separate PR for the removals, but that would have caused a merge conflict. So I figured I might as well add them here and see if you object :)

**Comment by obfusk** [comment]
I removed the unrelated changes. I'll make a separate PR for those later.

**Comment by TheLastProject** [comment]
Thanks, let's discuss the other stuff later and get this fix in now

**Pull request merged**
