### PR TITLE
added translation in bengali

### PR DESCRIPTION
**Pull request by avikkundu**
created a string file that contains translations into bengali

### CODE REVIEW

**Comment by avikkundu** [comment]
all requested changes have been made

**Comment by TheLastProject** [comment]
You did make some changes to app/src/main/res/values-bg/strings.xml (or added an old version maybe?)

Please resolve the conflicts (there's a button on GitHub, or just copy-paste the whole file from https://github.com/TheLastProject/Catima/blob/master/app/src/main/res/values-bg/strings.xml)

**Comment by avikkundu** [comment]
done

**Comment by avikkundu** [comment]
check now pls

**Pull request merged**
