### PR TITLE
app locale improvements

### PR DESCRIPTION
**Pull request by obfusk**
I removed Catalan (14 strings) and Welsh (4 strings) because I cannot imagine it's any use with so few strings.
Not sure about other languages, some have a little as 29% according to weblate.
Assuming for now we don't want to remove e.g. [Spanish (Argentina)](https://hosted.weblate.org/projects/catima/catima/es_AR/) (29%), I enabled [Asturian](https://hosted.weblate.org/projects/catima/catima/ast/) (29%) & [Luxembourgish](https://hosted.weblate.org/projects/catima/catima/lb/) (36%).

### CODE REVIEW

**Comment by TheLastProject** [comment]
Any reason to do the settings.xml manually? The reason Asturian and Luxembourgish were missing were because I forgot to manually update so I'd much prefer a solution that auto-generates all that's needed.

**Comment by TheLastProject** [comment]
I'm not a fan of removing languages automatically if they drop below a certain percentage. I did that with Pext thinking it would get people to maintain languages a bit more, but it did not have any such effect and just caused the issue that when the user chose a low% language the app would go back to system language and would never go back to the user's preferred option if the translation got extended.

Removing languages an user might have selected introduces a new possible source of bugs too.

I guess manually adding languages makes most sense, maybe I should just set up a calendar appointment to check once every few months if new options can be enabled. We should decide on some kind of policy of how much % is enough % though (maybe just 100% at time of inclusion because if the translator doesn't want to finish it the language probably won't be maintained either). But that's out of scope I guess. Will review this as-is later and test what happens if you're on a translation that gets removed.

**Comment by obfusk** [comment]
> I'm not a fan of removing languages automatically if they drop below a certain percentage.

Agreed. We could only add new ones if they go above a certain percentage. But maybe in a separate PR?

> test what happens if you're on a translation that gets removed.

IIRC it stays on that language but you would not be able to switch back. Should double-check that though.

And yeah, I certainly wanted your input before deciding to drop Catalan and Welsh as people might be using those. I just don't see how especially Welsh with 4 translated strings could possibly be useful. Catalan might have just enough useful strings that it helps someone that doesn't speak English. idk.

I don't like removing languages people might have selected, so I'm happy to re-add them. But 4 strings seems worse than not having it.

**Comment by obfusk** [comment]
> We should decide on some kind of policy of how much % is enough % though (maybe just 100% at time of inclusion because if the translator doesn't want to finish it the language probably won't be maintained either).

I just added some languages with ~30% because they'd be no worse than others. But idk what makes sense. Also hard to tell how much use a partial translation is to people that don't speak English.

Personally I'm not sure about removing Catalan (Welsh seems pointless), so I can re-add that if you prefer. But not including ast and lb would be odd since other languages are worse off. idk.

It's hard and I don't envy you the final decision :sweat_smile:

> But that's out of scope I guess.

Yeah. But happy to discuss and figure out something.

**Comment by obfusk** [comment]
> maybe I should just set up a calendar appointment to check once every few months if new options can be enabled.

We could e.g. have a CI job that runs on `strings.xml` changes and makes a PR to enable languages not enabled that exceed a certain amount of strings translated, either absolute or as a percentage of number of strings in en-US. idk. But happy to come up with something like that if you want.

**Comment by obfusk** [comment]
Maybe we should try to get some input from the translators if that's possible?

**Comment by obfusk** [comment]
> My main thought is: if a language never hits 100%, it is unlikely to be maintained long-term and users who depend on a translation to use the app will suffer if the completion keeps deteriorating more and more throughout releases. It feels like giving an user a "false promise'.

Yeah. I agree. But it also feels wrong (and inconsistent) to deny users a potentially useful partial translation when we have other languages with the same percentage. Which is why I enabled Asturian & Luxembourgish. But I don't know what's best here.

**Comment by TheLastProject** [comment]
I don't think we should consider consistency to be a big factor when we don't really know if the old behavior of me just enabling whatever made sense. Being consistent with bad decisions will just cause more bad decisions. We can just be more careful before we add new languages from now on.

**Comment by obfusk** [comment]
> Being consistent with bad decisions will just cause more bad decisions.

Agreed. Which is why I wanted your input on whether the changes make sense :)

Do you want me to disable Asturian & Luxembourgish again?

And do we want to keep other languages with the same low level of translation or not?

**Comment by TheLastProject** [comment]
I'm okay with removing Catalan and Welsh given their current state but let's not add any new languages and just have a script add those once they're at 100%.

**Comment by obfusk** [comment]
Ack. Will update the PR to reflect that. And will follow-up with automated detection of new languages reaching 100% later.

**Comment by obfusk** [comment]
> test what happens if you're on a translation that gets removed.

It changes to system. Will show as such in the in-app language chooser. But still show the removed language as selected in the "app info" language chooser, though it will no longer be available to select if you ever switch to anything else.

So it does show the wrong language in the "app info" chooser but doesn't break anything and otherwise behaves exactly as you'd expect it to.

**Pull request merged**
