### PR TITLE
Added Hindi Translation 

### PR DESCRIPTION
**Pull request by Abdullahkhanspn**
Added Hindi Translation in the code.

<string name="balanceParsingFailed">अमान्य शेष</string>

### CODE REVIEW

**Comment by Abdullahkhanspn** [comment]
I request please add (Hacktoberfest-accepted) label please . I want to translate more hindi translations if you give me this and Thanks .

**Comment by TheLastProject** [comment]
I can't accept this. As clearly written in CONTRIBUTING.md:

> Translation changes are managed through [Weblate](https://hosted.weblate.org/projects/catima/). Please do not supply translation updates directly through GitHub.

**Comment by Abdullahkhanspn** [comment]
but this is the different translation not before added or PR @TheLastProject  can you please tell me what to do ? I am new in this project and want to contribute in the Hindi Translation please .

**Comment by TheLastProject** [comment]
Please make translation changes on Weblate: https://hosted.weblate.org/projects/catima/-/hi/. More info on how to submit for Hacktoberfest I also put on that page :)

**Comment by Abdullahkhanspn** [comment]
okay thanks @TheLastProject

**Pull request closed without merging**
